use esmarProd
go

INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (1, 'Remojo', 100, 2138, 'AGUA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (1, '', 0.2, 1443, 'TECHSOL H-PLUS','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (1, '', 0.15, 1445, 'TECHSEPT 42  ','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (1, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (1, '', 150, 2138, 'AGUA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (1, '0', 0.25, 1446, 'TECHSEPT 30','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (1, '', 0.5, 1443, 'TECHSOL H-PLUS','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (1, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (1, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (1, '', 0.35, 1455, 'PELVIT MN','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (1, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (1, '', 0.35, 1134, 'ENZYMTECH R-50     ','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (1, '', 0.3, 492, 'CARBONATO DE SODIO','');

INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 30, 2138, 'AGUA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, 'Ajuste °Be', 0.1, 1468, 'SAL','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.7, 500, 'SULFIDRATO DE SODIO EN ESCAMAS','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.7, 1444, 'TECHAMINE TH-1','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.8, 1490, 'CAL','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.6, 1493, 'SULFURO DE SODIO','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.5, 1493, 'SULFURO DE SODIO','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.12, 1495, 'TRUPOTAN RK','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.8, 1490, 'CAL','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.06, 1495, 'TRUPOTAN RK','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.2, 1493, 'SULFURO DE SODIO','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.5, 1490, 'CAL','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.5, 1490, 'CAL','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.1, 1495, 'TRUPOTAN RK','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 20, 2138, 'AGUA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 1, 1490, 'CAL','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.25, 486, 'SOSA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 150, 2138, 'AGUA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 1.4, 1490, 'CAL','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.15, 1495, 'TRUPOTAN RK','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 50, 2138, 'AGUA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 1, 1490, 'CAL','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0.25, 486, 'SOSA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (2, '', 200, 2138, 'AGUA','');

INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 80, 2138, 'AGUA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0.4, 508, 'TECHSOL 5400','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0.2, 1457, 'METABISULFITO DE SODIO','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 10, 2138, 'AGUA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0.9, 1452, 'ACTIDEC BIO-AW','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0.8, 1692, 'SULFATO DE AMONIO','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 1.2, 1457, 'METABISULFITO DE SODIO','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0.5, 508, 'TECHSOL 5400','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0.8, 1441, 'CALTECH ES                                                 ','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0.15, 1442, 'ENZYMTECH 227 ','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0.4, 508, 'TECHSOL 5400','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 100, 2138, 'AGUA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 100, 2138, 'AGUA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 30, 2138, 'AGUA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0.05, 1480, 'SETA DE BLANK','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 6, 1468, 'SAL','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0.77, 1135, 'ACIDO FORMAICO AL 85%','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0.77, 1135, 'ACIDO FORMAICO AL 85%','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 1461, 'BLANCO TAN SN','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (3, '', 0, 1462, 'BLANCO TAN HLF','');

INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 20, 2138, 'AGUA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0.05, 1480, 'SETA DE BLANK','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 3, 1461, 'BLANCO TAN SN','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 1, 1462, 'BLANCO TAN HLF','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 1, 1473, 'RECURT FSA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 1, 1477, 'SETA SUN','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '1', 1, 1478, 'SETA SUPERSOL','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 1, 1477, 'SETA SUN','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '2', 1, 1478, 'SETA SUPERSOL','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0.12, 1488, 'SUPRA ESLIP 10','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0.3, 1472, 'RECURT DIS 116','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 2, 1478, 'SETA SUPERSOL','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '3', 1, 1477, 'SETA SUN','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '4', 5, 1477, 'SETA SUN','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 30, 2143, 'LICOR 15 ªBE','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '5', 0.05, 1480, 'SETA DE BLANK','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0.3, 1473, 'RECURT FSA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 5, 1460, 'QUEBRACHO ATO','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 1, 1481, 'SETA RC','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0.1, 1457, 'METABISULFITO DE SODIO','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0.5, 1703, 'SOFTY MT','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '6', 0.12, 1488, 'SUPRA ESLIP 10','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0.3, 1472, 'RECURT DIS 116','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '7', 6, 1460, 'QUEBRACHO ATO','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0.12, 1488, 'SUPRA ESLIP 10','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '8', 7, 1459, 'QUEBRACHO ATD','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '9', 8, 1459, 'QUEBRACHO ATD','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0.07, 1487, 'BUSAN 1280','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0.15, 1135, 'ACIDO FORMAICO AL 85%','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0.15, 1480, 'SETA DE BLANK','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0.15, 1453, 'ACIDO OXALICO','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 100, 2138, 'AGUA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 100, 2138, 'AGUA','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (4, '', 0.05, 1487, 'BUSAN 1280','');

INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 0.2, 1480, 'SETA DE BLANK','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 0.2, 1453, 'ACIDO OXALICO','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 0.2, 1457, 'METABISULFITO DE SODIO','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 2.5, 1695, 'AZUCAR ESTANDAR','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 1, 1466, 'SULFATO DE MAGNESIO','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 0.3, 1450, 'FORMIATO DE SODIO','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 7.5, 1476, 'SETA R25','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 3.8, 1703, 'SOFTY MT','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 0.4, 1694, 'SOFTY NEATS FOOT','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 0.4, 1449, 'CUIREMULL PB1','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 0, 0, '','');
INSERT INTO tb_insumXproc (idFormXSubProc, clave, porcentaje, idInsumo, nombreProducto, comentario) VALUES (5, '', 0.4, 1475, 'CURTAN BL','');