INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (1, 1, 'REMOJO', 100, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (2, 1, '', 0.2, 1443, 'TECHSOL H-PLUS');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (3, 1, '', 0.15, 1445, 'TECHSEPT 42  ');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (4, 1, '', 150, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (5, 1, '0', 0.25, 1446, 'TECHSEPT 30');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (6, 1, '', 0.5, 1443, 'TECHSOL H-PLUS');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (7, 1, '', 0.35, 1455, 'PELVIT MN');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (8, 1, '', 0.35, 1134, 'ENZYMTECH R-50     ');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (9, 1, '', 0.3, 492, 'CARBONATO DE SODIO');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (10, 2, '', 30, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (11, 2, '', 0.01, 1468, 'SAL');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (12, 2, '', 0.07, 500, 'SULFIDRATO DE SODIO EN ESCAMAS');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (13, 2, '', 0.07, 1444, 'TECHAMINE TH-1');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (14, 2, '', 0.8, 1490, 'CAL');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (15, 2, '', 0.6, 1493, 'SULFARO DE SODIO');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (16, 2, '', 0.5, 1493, 'SULFARO DE SODIO');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (17, 2, '', 0.12, 1495, 'TRUPOTAN RK');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (18, 2, '', 0.8, 1490, 'CAL');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (19, 2, '', 0.06, 1495, 'TRUPOTAN RK');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (20, 2, '', 0.2, 1493, 'SULFARO DE SODIO');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (21, 2, '', 0.5, 1490, 'CAL');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (22, 2, '', 0.5, 1490, 'CAL');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (23, 2, '', 0.1, 1495, 'TRUPOTAN RK');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (24, 2, '', 20, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (25, 2, '', 1, 1490, 'CAL');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (26, 2, '', 0.25, 486, 'SOSA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (27, 2, '', 150, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (28, 2, '', 1.4, 1490, 'CAL');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (29, 2, '', 0.15, 1495, 'TRUPOTAN RK');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (30, 2, '', 50, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (31, 2, '', 1, 1490, 'CAL');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (32, 2, '', 0.25, 486, 'SOSA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (33, 2, '', 200, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (34, 3, '', 80, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (35, 3, '', 0.4, 508, 'TECHSOL 5400');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (36, 3, '', 10, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (37, 3, '', 0.9, 1452, 'ACTIDEC BIO-AW');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (38, 3, '', 0.8, 1692, 'SULFATO DE AMONIO');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (39, 3, '', 0.5, 508, 'TECHSOL 5400');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (40, 3, '', 0.8, 1441, 'CALTECH ES                                                 ');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (41, 3, '', 0.15, 1442, 'ENZYMTECH 227 ');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (42, 3, '', 0.04, 508, 'TECHSOL 5400');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (43, 3, '', 100, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (44, 3, '', 100, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (45, 3, '', 30, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (46, 3, '', 0.05, 1480, 'SETA DE BLANK');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (47, 3, '', 6, 1468, 'SAL');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (48, 3, '', 0.77, 1135, 'ACIDO FORMAICO AL 85%');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (49, 3, '', 0.77, 1135, 'ACIDO FORMAICO AL 85%');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (50, 3, '', 0, 1461, 'BLANCO TAN SN');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (51, 3, '', 0, 1462, 'BLANCO TAN HLF');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (52, 4, '', 20, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (53, 4, '', 0.05, 1480, 'SETA DE BLANK');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (54, 4, '', 3, 1461, 'BLANCO TAN SN');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (55, 4, '', 1, 1462, 'BLANCO TAN HLF');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (56, 4, '', 1, 1473, 'RECURT FSA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (57, 4, '', 1, 1477, 'SETA SUN');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (58, 4, '', 1, 1477, 'SETA SUN');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (59, 4, '', 0.12, 1488, 'SUPRA ESLIP 10');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (60, 4, '', 0.3, 1472, 'RECURT DIS 116');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (61, 4, '', 1, 1477, 'SETA SUN');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (62, 4, '', 5, 1477, 'SETA SUN');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (63, 4, '', 0.05, 1480, 'SETA DE BLANK');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (64, 4, '', 0.3, 1473, 'RECURT FSA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (65, 4, '', 5, 1460, 'QUEBRACHO ATO');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (66, 4, '', 1, 1481, 'SETA RC');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (67, 4, '', 0.5, 1703, 'SOFTY MT');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (68, 4, '', 0.12, 1488, 'SUPRA ESLIP 10');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (69, 4, '', 0.3, 1472, 'RECURT DIS 116');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (70, 4, '', 6, 1460, 'QUEBRACHO ATO');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (71, 4, '', 0.12, 1488, 'SUPRA ESLIP 10');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (72, 4, '', 7, 1459, 'QUEBRACHO ATD');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (73, 4, '', 8, 1459, 'QUEBRACHO ATD');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (74, 4, '', 0.07, 1487, 'BUSAN 1280');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (75, 4, '', 0.15, 1135, 'ACIDO FORMAICO AL 85%');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (76, 4, '', 0.15, 1480, 'SETA DE BLANK');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (77, 4, '', 0.15, 1453, 'ACIDO OXALICO');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (78, 4, '', 100, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (79, 4, '', 100, 2138, 'AGUA');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (80, 4, '', 0.05, 1487, 'BUSAN 1280');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (81, 5, '', 0.2, 1480, 'SETA DE BLANK');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (82, 5, '', 0.2, 1453, 'ACIDO OXALICO');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (83, 5, '', 2.5, 1695, 'AZUCAR ESTANDAR');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (84, 5, '', 1, 1466, 'SULFATO DE MAGNESIO');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (85, 5, '', 0.3, 1450, 'FORMIATO DE SODIO');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (86, 5, '', 7.5, 1476, 'SETA R25');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (87, 5, '', 3.8, 1703, 'SOFTY MT');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (88, 5, '', 0.4, 1694, 'SOFTY NEATS FOOT');
INSERT INTO "tb_insumXproc" ("idInsumXProc", "idFormXSubProc", "clave", "porcentaje", "idInsumo", "nombreProducto") VALUES (89, 5, '', 0.4, 1475, 'CURTAN BL');
